"""Host memory — persistent observations about each host.

Auto-generated by the agent from scan results, editable by the red teamer
via the web UI, and fed back into the LLM system prompt for smarter
decision-making. Exportable as JSON for Thor.

Memory format per host:
{
    "ip": "unknown",
    "mac": "DC:A6:32:5C:8D:5F",
    "observations": [
        {"source": "agent", "text": "Pi-hole DNS sinkhole (HTTP 403)", "ts": "..."},
        {"source": "agent", "text": "Samba 4.17.12 with null-session shares: share, nobody", "ts": "..."},
        {"source": "analyst", "text": "Known Raspberry Pi, check for default creds", "ts": "..."},
    ],
    "tags": ["pi-hole", "samba", "ssh"],
    "status": "interesting",  # interesting | dead-end | compromised | needs-attention
    "avoid_tools": ["nmap"],  # tools that won't help on this host
    "last_updated": "..."
}
"""

import re
import time
from agent import db


def _ts():
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def get_all_memories() -> dict:
    """Get all host memories. Key is MAC address."""
    return db.get_state("host_memories", {})


def get_memory(mac: str) -> dict:
    """Get memory for a specific host."""
    memories = get_all_memories()
    return memories.get(mac, {})


def set_memory(mac: str, memory: dict):
    """Set memory for a specific host."""
    memories = get_all_memories()
    memory["last_updated"] = _ts()
    memories[mac] = memory
    db.set_state("host_memories", memories)


MAX_OBS_PER_HOST = 30  # prevent memory bloat in system prompt


def add_observation(mac: str, text: str, source: str = "agent",
                    ip: str = ""):
    """Add an observation to a host's memory. Auto-prunes old entries."""
    memories = get_all_memories()
    if mac not in memories:
        memories[mac] = {
            "ip": ip, "mac": mac, "observations": [],
            "tags": [], "status": "unknown", "avoid_tools": [],
        }
    # Don't add duplicate observations
    existing = [o["text"] for o in memories[mac].get("observations", [])]
    if text not in existing:
        memories[mac]["observations"].append({
            "source": source, "text": text, "ts": _ts()
        })
        # Prune: keep analyst obs + latest N agent obs
        obs = memories[mac]["observations"]
        if len(obs) > MAX_OBS_PER_HOST:
            analyst = [o for o in obs if o.get("source") == "analyst"]
            agent = [o for o in obs if o.get("source") != "analyst"]
            memories[mac]["observations"] = analyst + agent[-(MAX_OBS_PER_HOST - len(analyst)):]
        memories[mac]["ip"] = ip or memories[mac].get("ip", "")
        memories[mac]["last_updated"] = _ts()
        db.set_state("host_memories", memories)


def update_status(mac: str, status: str):
    """Update host status: interesting, dead-end, compromised, needs-attention."""
    memory = get_memory(mac)
    if memory:
        memory["status"] = status
        set_memory(mac, memory)


def add_tag(mac: str, tag: str):
    """Add a tag to a host."""
    memory = get_memory(mac)
    if memory and tag not in memory.get("tags", []):
        memory.setdefault("tags", []).append(tag)
        set_memory(mac, memory)


def set_avoid_tools(mac: str, tools: list):
    """Set tools to avoid for this host."""
    memory = get_memory(mac)
    if memory:
        memory["avoid_tools"] = tools
        set_memory(mac, memory)


def auto_extract_observations(ip: str, mac: str, command: str,
                               output: str, status: str):
    """Auto-generate observations from command results.
    Learns from BOTH successes and failures."""

    # Learn from errors — these are valuable intelligence
    if status == "error" or (status == "success" and not output.strip()):
        out_lower = (output or "").lower()
        if "nt_status_io_timeout" in out_lower or "connection timed out" in out_lower:
            add_observation(mac, f"Connection timeout — host may be firewalled",
                            source="agent", ip=ip)
            update_status(mac, "dead-end")
        elif "host seems down" in out_lower:
            add_observation(mac, f"Host down (nmap: not responding to probes)",
                            source="agent", ip=ip)
            update_status(mac, "dead-end")
        elif "connection refused" in out_lower:
            add_observation(mac, f"Connection refused on probed port",
                            source="agent", ip=ip)
        elif "filtered" in out_lower:
            add_observation(mac, f"Ports filtered/closed — skip nmap, try other tools",
                            source="agent", ip=ip)
        if not output.strip() and "curl" in command:
            add_observation(mac, f"curl returned empty — service may not be HTTP",
                            source="agent", ip=ip)
        if not output.strip() and "https" in command.lower():
            add_observation(mac, f"HTTPS failed — try HTTP instead",
                            source="agent", ip=ip)
        return

    if status != "success":
        return

    # Record failed credential attacks (nxc, sshpass, hydra)
    # so the agent doesn't retry the same creds on the same host
    if any(t in command for t in ['nxc ', 'sshpass ', 'hydra ']):
        # VNC: nxc vnc often returns empty output or [*] RFB without [+]
        # on failure — treat both empty and [*]-without-[+] as failure
        is_vnc_no_success = ('vnc' in command.lower() and '[+]' not in output)
        if '[-]' in output or 'AUTH FAILED' in output.upper() or is_vnc_no_success:
            # Extract user:pass from the command
            user_match = re.search(r'-u\s+(\S+)', command)
            pass_match = re.search(r"-p\s+'?([^'\s]+)", command)
            if not pass_match:
                pass_match = re.search(r'-p\s+(\S+)', command)
            if pass_match:
                user = user_match.group(1) if user_match else ""
                passwd = pass_match.group(1)
                # Truncate wordlist paths
                if '/' in passwd:
                    passwd = passwd.split('/')[-1]
                proto = 'SSH'
                if 'smb' in command: proto = 'SMB'
                elif 'vnc' in command: proto = 'VNC'
                elif 'telnet' in command: proto = 'TELNET'
                elif 'ftp' in command: proto = 'FTP'
                add_observation(mac, f"FAILED {proto} {user}:{passwd}",
                                source="agent", ip=ip)
        elif '[+]' in output or 'SUCCESS' in output.upper():
            add_observation(mac, f"ACCESS GAINED via {command[:60]}",
                            source="agent", ip=ip)
            update_status(mac, "compromised")
            add_tag(mac, "pwned")
            # Record formal credential in DB
            try:
                user_match = re.search(r'-u\s+(\S+)', command)
                pass_match = re.search(r"-p\s+'?([^'\s]+)", command)
                if not pass_match:
                    pass_match = re.search(r'-p\s+(\S+)', command)
                if user_match and pass_match:
                    proto = 'ssh'
                    if 'smb' in command: proto = 'smb'
                    elif 'vnc' in command: proto = 'vnc'
                    elif 'telnet' in command: proto = 'telnet'
                    elif 'ftp' in command: proto = 'ftp'
                    db.add_credential(proto, user_match.group(1),
                                      pass_match.group(1), ip)
            except Exception:
                pass

    # Record recon tool attempts so agent doesn't repeat them
    if "searchsploit" in command:
        parts = command.split("searchsploit", 1)[1].strip()
        if parts:
            add_observation(mac, f"TRIED searchsploit {parts[:40]}",
                            source="agent", ip=ip)

    if "dig" in command and "axfr" in command:
        add_observation(mac, "TRIED axfr zone transfer",
                        source="agent", ip=ip)

    if "enum4linux" in command:
        add_observation(mac, "TRIED enum4linux", source="agent", ip=ip)

    if "nikto" in command:
        add_observation(mac, "TRIED nikto web scan", source="agent", ip=ip)

    if "impacket-samrdump" in command:
        add_observation(mac, "TRIED impacket-samrdump", source="agent", ip=ip)

    if "impacket-rpcdump" in command:
        add_observation(mac, "TRIED impacket-rpcdump", source="agent", ip=ip)

    observations = []

    # HTTP server identification + content analysis
    if "curl" in command and ("Server:" in output or "HTTP/" in output):
        server_match = re.search(r'Server:\s*(.+)', output)
        if server_match:
            observations.append(f"HTTP server: {server_match.group(1).strip()[:80]}")
        if "403" in output:
            observations.append("HTTP 403 Forbidden — login/auth required")
        if "pi-hole" in output.lower() or "Pi-hole" in output:
            observations.append("Pi-hole DNS sinkhole detected")
            add_tag(mac, "pi-hole")

    # HTTP content analysis — extract frameworks, login forms, internal IPs
    if "curl" in command and output.strip() and "<" in output:
        try:
            from agent.recon_tools import parse_http_content
            url = re.search(r'https?://\S+', command)
            url_str = url.group() if url else ""
            http_findings = parse_http_content(ip, url_str, output)
            for finding in http_findings[:3]:  # max 3 per response
                observations.append(f"HTTP analysis: {finding[:80]}")
        except Exception:
            pass

    # Hostname extraction — from nmap, dig, nbns, smbclient
    hostname_found = None
    # nmap: "Nmap scan report for hostname (ip)" or "Nmap scan report for ip"
    nmap_host = re.search(r'Nmap scan report for (\S+)\s+\(', output)
    if nmap_host and not nmap_host.group(1).replace('.','').isdigit():
        hostname_found = nmap_host.group(1)
    # dig -x reverse DNS
    if "dig" in command and "-x" in command and "PTR" in output:
        ptr = re.search(r'PTR\s+(\S+?)\.?\s*$', output, re.MULTILINE)
        if ptr:
            hostname_found = ptr.group(1).rstrip('.')
    # nbns/netbios name from nmap
    nbname = re.search(r'NetBIOS name:\s*(\S+)', output)
    if nbname:
        hostname_found = nbname.group(1)
    # SMB workgroup/hostname
    smb_name = re.search(r'Domain:\s*\[([^\]]+)\].*OS:\s*\[([^\]]*)\]', output)
    if smb_name:
        hostname_found = hostname_found or smb_name.group(1)

    if hostname_found and ip:
        try:
            import sqlite3
            conn = sqlite3.connect(db.DB_PATH)
            conn.execute("UPDATE hosts SET hostname=? WHERE ip=? AND (hostname IS NULL OR hostname='')",
                         (hostname_found, ip))
            conn.commit()
            conn.close()
            observations.append(f"Hostname: {hostname_found}")
        except Exception:
            pass

    # SSH version
    if "OpenSSH" in output:
        ssh_match = re.search(r'OpenSSH\s+(\S+)', output)
        if ssh_match:
            observations.append(f"SSH: OpenSSH {ssh_match.group(1)}")
            add_tag(mac, "ssh")

    # SMB shares
    if "smbclient" in command and ("Sharename" in output or "IPC$" in output):
        shares = re.findall(r'^\s+(\S+)\s+Disk', output, re.MULTILINE)
        if shares:
            observations.append(f"SMB shares accessible: {', '.join(shares)}")
            add_tag(mac, "smb")
            # Record as vulnerability — unauthenticated SMB share access
            try:
                db.add_vulnerability(
                    ip, "smb",
                    f"[MISCONFIG] Null-session SMB shares: {', '.join(shares)} — "
                    f"CVE-2017-7494 (SambaCry RCE if Samba <4.6.4)",
                    "medium",
                    chain=f"smbclient -N -L //{ip}/ → shares: {', '.join(shares)}")
            except Exception:
                pass
        samba_ver = re.search(r'Samba\s+(\S+)', output)
        if samba_ver:
            observations.append(f"Samba version: {samba_ver.group(1)}")

    # Pi-hole admin exposed — detailed analysis with CVE tagging
    if "curl" in command and ("pi-hole" in output.lower() or "Pi-hole" in output):
        try:
            detail = "Pi-hole admin panel"
            severity = "medium"
            chain_detail = f"{command[:80]} → "
            if "-X POST" in command and "pw=" in command:
                # Login attempt — check if it worked
                pw_match = re.search(r"pw=(\S+)'?", command)
                pw_val = pw_match.group(1).rstrip("'") if pw_match else "?"
                if "Forgot password" not in output and "Invalid" not in output and len(output.strip()) > 100:
                    detail = (f"[MISCONFIG] Pi-hole admin login may accept pw={pw_val} "
                              f"(got non-error response {len(output)}B) — "
                              f"CVE-2020-8816 (RCE via MAC bypass if authenticated), "
                              f"CVE-2021-29449 (authenticated RCE via settings)")
                    severity = "high"
                    chain_detail += f"POST pw={pw_val} → {len(output)}B response (no error)"
                else:
                    # Login rejected — not a vuln, skip recording
                    detail = None
            elif "api.php" in command:
                if output.strip() and "status" in output.lower():
                    detail = (f"[MISCONFIG] Pi-hole API exposed without auth — "
                              f"status endpoint accessible — "
                              f"CVE-2022-23513 (broken access control)")
                    severity = "high"
                    chain_detail += f"API returned: {output[:100]}"
                else:
                    detail = f"Pi-hole API endpoint responded ({len(output)}B)"
                    severity = "medium"
                    chain_detail += f"API {len(output)}B response"
            elif "403" in output:
                detail = (f"Pi-hole admin panel at /admin (HTTP 403) — "
                          f"CVE-2020-11108 (RCE if auth obtained), "
                          f"CVE-2020-35591 (CORS misconfiguration)")
                chain_detail += "HTTP 403 → panel exists, auth required"
            else:
                detail = f"Pi-hole admin panel detected ({len(output)}B)"
                chain_detail += f"Pi-hole HTML detected ({len(output)}B)"
            if detail:
                db.add_vulnerability(ip, "http", detail, severity, chain=chain_detail)
        except Exception:
            pass

    # HTTP sensitive files
    if "curl" in command:
        if ".env" in command and output.strip() and "404" not in output:
            try:
                db.add_vulnerability(ip, "http", ".env file exposed (possible credential leak)",
                                     "high")
            except Exception:
                pass
        if "robots.txt" in command and output.strip() and "404" not in output and "Disallow" in output:
            try:
                db.add_vulnerability(ip, "http", f"robots.txt exposes paths: {output[:100]}",
                                     "low")
            except Exception:
                pass
        if "server-status" in command and "200" in output:
            try:
                db.add_vulnerability(ip, "http", "Apache server-status exposed",
                                     "medium")
            except Exception:
                pass

    # DNS zone transfer success
    if "dig" in command and "axfr" in command and "XFR size" in output:
        try:
            db.add_vulnerability(ip, "dns",
                                 "[MISCONFIG] DNS zone transfer allowed (AXFR) — "
                                 "exposes internal hostnames and network topology",
                                 "high")
        except Exception:
            pass

    # DNS
    if "dig" in command and "NOERROR" in output:
        observations.append("DNS resolver responding")
        add_tag(mac, "dns")

    # Nmap NSE vuln findings
    if "nmap" in command and "--script=" in command:
        if "VULNERABLE" in output:
            vuln_match = re.search(r'(CVE-\d{4}-\d+|ms\d{2}-\d+)', output, re.IGNORECASE)
            vuln_name = vuln_match.group(1) if vuln_match else "NSE vuln detected"
            script_match = re.search(r'--script=(\S+)', command)
            service = script_match.group(1).replace('*','') if script_match else "unknown"
            try:
                db.add_vulnerability(ip, service, f"VULNERABLE: {vuln_name} ({output[:100]})",
                                     "critical")
            except Exception:
                pass
        # CVE findings from vulners
        if "CVE-" in output:
            cves = re.findall(r'(CVE-\d{4}-\d+)', output)
            for cve in cves[:3]:  # max 3 per scan
                try:
                    db.add_vulnerability(ip, "ssh", f"CVE found: {cve}", "medium")
                except Exception:
                    pass

    # VNC no-auth
    if "vnc" in command.lower() and ("Authentication: None" in output or
                                      "[+]" in output):
        try:
            db.add_vulnerability(ip, "vnc",
                                 "[MISCONFIG] VNC no authentication required — "
                                 "CVE-2006-2369 (RealVNC auth bypass)",
                                 "critical")
        except Exception:
            pass

    # FTP anonymous access
    if ("ftp" in command.lower() and "anonymous" in command.lower() and
            "[+]" in output):
        try:
            db.add_vulnerability(ip, "ftp",
                                 "[MISCONFIG] FTP anonymous access allowed — "
                                 "data exfiltration risk",
                                 "medium")
        except Exception:
            pass

    # Nmap service versions + auto-tag for playbook triggers
    if "nmap" in command and "open" in output:
        services = re.findall(r'(\d+)/tcp\s+open\s+(\S+)\s*(.*)', output)
        for port, svc, version in services:
            ver_lower = (svc + " " + version).lower()
            if version.strip():
                observations.append(f"Port {port}/{svc}: {version.strip()[:60]}")
            # Auto-tag services for playbook triggers
            if "wordpress" in ver_lower:
                add_tag(mac, "wordpress")
            if "tomcat" in ver_lower:
                add_tag(mac, "tomcat")
            if "jenkins" in ver_lower:
                add_tag(mac, "jenkins")
            if "joomla" in ver_lower:
                add_tag(mac, "joomla")
            if "phpmyadmin" in ver_lower:
                add_tag(mac, "phpmyadmin")

        # Also detect UDP services in output
        udp_services = re.findall(r'(\d+)/udp\s+open\s+(\S+)\s*(.*)', output)
        for port, svc, version in udp_services:
            if version.strip():
                observations.append(f"Port {port}/{svc} (UDP): {version.strip()[:60]}")

    # Auto-detect service names in any nmap/nxc output for playbook triggers
    if "nmap" in command or "nxc" in command:
        out_lower = output.lower()
        service_tags = {
            "snmp": ["snmp", "161/udp"],
            "ldap": ["ldap", "389/tcp", "636/tcp"],
            "smtp": ["smtp", "25/tcp", "587/tcp"],
            "rdp": ["ms-wbt-server", "3389/tcp", "rdp"],
            "nfs": ["nfs", "2049/tcp", "111/tcp.*rpcbind"],
            "mongodb": ["mongodb", "27017/tcp"],
            "ms-sql": ["ms-sql", "1433/tcp", "mssql"],
            "docker": ["docker", "2375/tcp", "2376/tcp"],
            "ipmi": ["ipmi", "623/udp"],
            "postgres": ["postgresql", "5432/tcp", "postgres"],
        }
        for tag, patterns in service_tags.items():
            if any(p in out_lower for p in patterns):
                add_tag(mac, tag)

    # All ports filtered
    if "nmap" in command and "All" in output and "filtered" in output:
        add_observation(mac, "All scanned ports filtered — host is firewalled",
                        source="agent", ip=ip)
        update_status(mac, "dead-end")
        return

    for obs in observations:
        add_observation(mac, obs, source="agent", ip=ip)


def build_prompt_context(max_tokens: int = 300, network_id: str = None) -> str:
    """Build a concise memory context for the LLM system prompt.
    Prioritizes interesting hosts and recent observations.

    When network_id is provided, only include memories for hosts in that
    network. This prevents the LLM from seeing (and targeting) hosts from
    previous engagements/networks.
    """
    memories = get_all_memories()
    if not memories:
        return ""

    if network_id:
        # Filter memories down to hosts that live in this network according to DB.
        try:
            scoped_macs = {h.get("mac") for h in db.get_hosts(network_id=network_id) if h.get("mac")}
            scoped_ips = {h.get("ip") for h in db.get_hosts(network_id=network_id) if h.get("ip")}
            memories = {
                mac: mem for mac, mem in memories.items()
                if mac in scoped_macs or mem.get("ip") in scoped_ips
            }
            if not memories:
                return ""
        except Exception:
            pass

    lines = []
    char_budget = max_tokens * 4  # rough chars-to-tokens

    # Sort: interesting first, then by last_updated
    sorted_macs = sorted(memories.keys(),
                         key=lambda m: (
                             0 if memories[m].get("status") == "interesting" else
                             1 if memories[m].get("status") == "needs-attention" else
                             2 if memories[m].get("status") == "unknown" else 3,
                             memories[m].get("last_updated", "")
                         ), reverse=False)

    for mac in sorted_macs:
        mem = memories[mac]
        ip = mem.get("ip", "?")
        status = mem.get("status", "")
        tags = mem.get("tags", [])
        avoid = mem.get("avoid_tools", [])
        obs = mem.get("observations", [])

        # Build compact line with port info
        parts = [f"{ip}"]

        # Include ports from DB for tool matching (scoped to network if known).
        try:
            host_list = (db.get_hosts(network_id=network_id)
                         if network_id else db.get_hosts())
            for h in host_list:
                if h.get("mac") == mac or h.get("ip") == ip:
                    ports = h.get("ports", [])
                    if ports:
                        parts.append(f"ports:{','.join(str(p) for p in ports[:6])}")
                    break
        except Exception:
            pass

        if status and status != "unknown":
            parts.append(f"[{status}]")
        if tags:
            parts.append(f"tags:{','.join(tags[:3])}")
        if avoid:
            parts.append(f"skip:{','.join(avoid)}")
        # Latest 2 observations
        for o in obs[-2:]:
            parts.append(o["text"][:60])

        # Show failed command count as a compact indicator
        failed = mem.get("failed_commands", [])
        if failed:
            parts.append(f"fails:{len(failed)}")

        line = " | ".join(parts)
        if len("\n".join(lines)) + len(line) > char_budget:
            break
        lines.append(f"  {line}")

    if not lines:
        return ""

    result = "HOST MEMORY:\n" + "\n".join(lines)

    # Append per-host failed command hints for hosts with failures
    # (compact: only show for hosts with 3+ failures to save tokens)
    for mac in sorted_macs:
        mem = memories[mac]
        failed = mem.get("failed_commands", [])
        if len(failed) >= 3:
            ip = mem.get("ip", "?")
            hints = build_failed_command_hints(mac, max_hints=3)
            if hints:
                section = f"\n{ip} {hints}"
                if len(result) + len(section) > char_budget:
                    break
                result += section

    return result


MAX_FAILED_COMMANDS = 15  # max failed commands tracked per host


def _normalize_command(command: str, ip: str = "") -> str:
    """Normalize a command by replacing the target IP with <IP>.

    This allows dedup across DHCP changes on the same host.
    """
    normalized = command.strip()
    if ip:
        normalized = normalized.replace(ip, "<IP>")
    # Also replace any private IPs that look like targets
    normalized = re.sub(r'\b(?:192\.168\.\d+\.\d+|10\.\d+\.\d+\.\d+|172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+)\b',
                        '<IP>', normalized)
    return normalized


def _extract_failure_reason(output: str) -> str:
    """Extract a short failure reason from command output."""
    if not output or not output.strip():
        return "empty response"
    out_lower = output.lower()
    # Check common failure patterns (order matters — most specific first)
    patterns = [
        ("connection refused", "connection refused"),
        ("connection timed out", "connection timed out"),
        ("nt_status_io_timeout", "SMB timeout"),
        ("nt_status_connection_refused", "SMB connection refused"),
        ("nt_status_access_denied", "access denied"),
        ("nt_status_logon_failure", "logon failure"),
        ("host seems down", "host down"),
        ("no route to host", "no route to host"),
        ("name or service not known", "DNS resolution failed"),
        ("transfer failed", "transfer failed"),
        ("axfr failed", "AXFR failed"),
        ("404 not found", "404 Not Found"),
        ("404", "404"),
        ("403 forbidden", "403 Forbidden"),
        ("401 unauthorized", "401 Unauthorized"),
        ("timed out", "timed out"),
        ("timeout", "timeout"),
        ("refused", "refused"),
        ("failed", "failed"),
        ("not found", "not found"),
        ("error", "error"),
    ]
    for pattern, reason in patterns:
        if pattern in out_lower:
            return reason
    # Fallback: first non-empty line, truncated
    for line in output.strip().splitlines():
        line = line.strip()
        if line and not line.startswith('#'):
            return line[:60]
    return "unknown error"


def record_failed_command(mac: str, command: str, output: str, ip: str = ""):
    """Record a failed command for a host to prevent retries.

    Normalizes the command (strips IP) so dedup works across DHCP changes.
    Keeps max MAX_FAILED_COMMANDS entries per host (prunes oldest).
    """
    try:
        memories = get_all_memories()
        if mac not in memories:
            memories[mac] = {
                "ip": ip, "mac": mac, "observations": [],
                "tags": [], "status": "unknown", "avoid_tools": [],
            }

        normalized = _normalize_command(command, ip)
        reason = _extract_failure_reason(output)

        failed = memories[mac].get("failed_commands", [])

        # Don't add duplicates (same normalized command)
        for entry in failed:
            if entry.get("cmd") == normalized:
                # Update reason and timestamp
                entry["reason"] = reason
                entry["ts"] = _ts()
                memories[mac]["last_updated"] = _ts()
                db.set_state("host_memories", memories)
                return

        failed.append({
            "cmd": normalized,
            "reason": reason,
            "ts": _ts(),
        })

        # Prune oldest if over limit
        if len(failed) > MAX_FAILED_COMMANDS:
            failed = failed[-MAX_FAILED_COMMANDS:]

        memories[mac]["failed_commands"] = failed
        memories[mac]["ip"] = ip or memories[mac].get("ip", "")
        memories[mac]["last_updated"] = _ts()
        db.set_state("host_memories", memories)
    except Exception:
        pass  # never crash the agent


def build_failed_command_hints(mac: str, max_hints: int = 5) -> str:
    """Build a prompt hint listing failed commands for a host.

    Returns a string like:
        FAILED ON THIS HOST (do not retry):
          - dig axfr: Transfer failed
          - curl /.env: 404 Not Found

    Returns empty string if no failed commands.
    """
    try:
        mem = get_memory(mac)
        if not mem:
            return ""
        failed = mem.get("failed_commands", [])
        if not failed:
            return ""

        # Show most recent failures (last N)
        recent = failed[-max_hints:]
        lines = []
        for entry in recent:
            # Shorten the command for display
            cmd = entry.get("cmd", "")
            # Extract just the tool + key args (first 50 chars)
            short_cmd = cmd[:50].rstrip()
            reason = entry.get("reason", "failed")
            lines.append(f"  - {short_cmd}: {reason}")

        if not lines:
            return ""
        return "FAILED ON THIS HOST (do not retry):\n" + "\n".join(lines)
    except Exception:
        return ""


def get_host_priority(mac: str) -> str:
    """Classify host for weighted selection during exploit phase.

    Returns: 'high' | 'medium' | 'low' | 'exhausted'
    - high: confirmed open access (shares, admin panels, services responding)
    - medium: has ports but no findings yet (untested)
    - low: only failed attacks recorded
    - exhausted: many failed attacks, no successes (deprioritize)
    """
    mem = get_memory(mac)
    if not mem:
        return "medium"

    obs_texts = [o["text"] for o in mem.get("observations", [])]
    status = mem.get("status", "unknown")

    if status == "compromised":
        return "high"
    if status == "dead-end":
        return "low"

    # Count confirmed access (not just "has a port open")
    access_indicators = sum(1 for t in obs_texts if any(w in t for w in [
        "shares accessible", "Pi-hole detected", "Pi-hole DNS",
        "ACCESS GAINED", "Samba version",
        "dnsmasq", "DNS resolver responding",
    ]))
    failed_attacks = sum(1 for t in obs_texts if t.startswith("FAILED "))

    if access_indicators > 0:
        return "high"
    if failed_attacks >= 5:
        return "exhausted"
    if failed_attacks >= 3:
        return "low"
    return "medium"


def get_failed_attacks(mac: str) -> list:
    """Get list of failed attack strings for a host (for dedup in hints)."""
    mem = get_memory(mac)
    if not mem:
        return []
    return [o["text"] for o in mem.get("observations", [])
            if o["text"].startswith("FAILED ")]


def mark_playbook_done(mac: str, playbook_id: str, ip: str = ""):
    """Mark a playbook as completed for this host. Persists in SQLite."""
    add_observation(mac, f"PLAYBOOK_DONE {playbook_id}", source="agent", ip=ip)


def is_playbook_done(mac: str, playbook_id: str) -> bool:
    """Check if a playbook was already run on this host."""
    mem = get_memory(mac)
    if not mem:
        return False
    return any(o["text"] == f"PLAYBOOK_DONE {playbook_id}"
               for o in mem.get("observations", []))


def mark_playbook_failed(mac: str, playbook_id: str, ip: str = ""):
    """Mark a playbook as ineffective for this host."""
    add_observation(mac, f"PLAYBOOK_FAILED {playbook_id}", source="agent", ip=ip)


def is_playbook_failed(mac: str, playbook_id: str) -> bool:
    """Check if a playbook already failed on this host."""
    mem = get_memory(mac)
    if not mem:
        return False
    return any(o["text"] == f"PLAYBOOK_FAILED {playbook_id}"
               for o in mem.get("observations", []))


def get_tried_actions(mac: str) -> list:
    """Get list of already-tried tool strings for hint dedup."""
    mem = get_memory(mac)
    if not mem:
        return []
    return [o["text"] for o in mem.get("observations", [])
            if o["text"].startswith("TRIED ")]


def get_access_findings(mac: str) -> list:
    """Get confirmed access findings for exploit depth hints."""
    mem = get_memory(mac)
    if not mem:
        return []
    access_words = ["shares accessible", "Pi-hole", "HTTP server",
                    "HTTP 403", "VNC", "Samba version", "DNS resolver",
                    "dnsmasq", "admin", "ACCESS GAINED"]
    return [o["text"] for o in mem.get("observations", [])
            if any(w in o["text"] for w in access_words)]


def export_memories() -> dict:
    """Export all host memories for Thor."""
    return {
        "export_time": _ts(),
        "host_memories": get_all_memories(),
        "network_memories": get_all_network_memories(),
    }


# ── Network-level memories ───────────────────────────

def get_all_network_memories() -> dict:
    """Get all network memories. Key is network_id."""
    return db.get_state("network_memories", {})


def get_network_memory(network_id: str) -> dict:
    """Get memory for a specific network."""
    memories = get_all_network_memories()
    return memories.get(network_id, {})


def add_network_observation(network_id: str, text: str,
                            source: str = "agent"):
    """Add an observation to a network's memory."""
    memories = get_all_network_memories()
    if network_id not in memories:
        memories[network_id] = {
            "network_id": network_id, "observations": [],
            "scanned_ips": [], "tags": [],
        }
    existing = [o["text"] for o in memories[network_id].get("observations", [])]
    if text not in existing:
        memories[network_id]["observations"].append({
            "source": source, "text": text, "ts": _ts()
        })
        memories[network_id]["last_updated"] = _ts()
        db.set_state("network_memories", memories)


def mark_ip_scanned(network_id: str, ip: str):
    """Track that an IP has been scanned on this network."""
    memories = get_all_network_memories()
    if network_id not in memories:
        memories[network_id] = {
            "network_id": network_id, "observations": [],
            "scanned_ips": [], "tags": [],
        }
    if ip not in memories[network_id].get("scanned_ips", []):
        memories[network_id].setdefault("scanned_ips", []).append(ip)
        memories[network_id]["last_updated"] = _ts()
        db.set_state("network_memories", memories)


def build_network_prompt_context(network_id: str, max_tokens: int = 100) -> str:
    """Build compact network context for the LLM."""
    mem = get_network_memory(network_id)
    if not mem:
        return ""
    parts = []
    scanned = mem.get("scanned_ips", [])
    if scanned:
        parts.append(f"Scanned IPs: {', '.join(scanned[-10:])}")
    for o in mem.get("observations", [])[-3:]:
        parts.append(o["text"][:60])
    if not parts:
        return ""
    return "NETWORK CONTEXT:\n  " + "\n  ".join(parts)
